#!/bin/sh
	DIRECTORY=$(pwd)
	t=$( find -maxdepth 1 -mindepth 1 -type d |  sed "s@\./@@g")
	if [ "$t" == "." ]; then 
		t=""
	fi
	if [  "$t" != "" ]; then
		i=$(echo -e "$t\n.." | fzy)
		while [ -d "$i" ]; do
			cd $DIRECTORY/$i
			DIRECTORY=$DIRECTORY/$i
			t=$(find -maxdepth 1 -mindepth 1 -type d)
			echo $t
			if [ "$t" == "."]; then
				t=""
			fi
			if [  "$t" != "" ]; then
				i=$(printf "$t\n.." | fzy)
			else
				break
			fi
			if [ "$i" == "" ]; then 
				break
			fi
		done
	fi
