#!/bin/bash
if [ "$(echo $1 | sed -n /.*\.mkv/p)" != "" ]; then eval "vlc $1"; fi 
if [ "$(echo $1 | sed -n /.*\.mp4/p)" != "" ]; then eval "vlc $1"; fi 
if [ "$(echo $1 | sed -n /.*\.jpg/p)" != "" ]; then eval "xviewer $1"; fi 
if [ "$(echo $1 | sed -n /.*\.png/p)" != "" ]; then eval "xviewer $1"; fi 
if [ "$(echo $1 | sed -n /.*\.html/p)" != "" ]; then eval "firefox $1"; fi 
if [ "$(echo $1 | sed -n /.*\.txt/p)" != "" ]; then eval "e $1"; fi 
