#!/bin/bash 
h=$(cisco state | sed -n  '/Connected/p' | sed -n  '1s/.*/1/gp')
if [ "$h" == "1" ]
then dis.sh
else rec
fi


h=$(cisco state | sed -n  '/Connected/p' | sed -n  '1s/.*/1/gp'); if [ "$h" == "1" ] then;  echo -e "put -r .scripts/ \n quit" | sftp pi@10.41.3.81 ; done; fi 
