
/* get maximum User_ID */ 

SELECT MAX(NUTZERID) as MAX_ID from NUTZER;

/* You will need this for getting the actual VALUE of the of NUTZERID */ 

SELECT MAX(YOURTYPE) as MAX_ID from yourtype;

/* CREATE USER */

INSERT into swt.NUTZER(NUTZERID,PASSWORD) VALUES (*NUTZERID*, "PASSWORD");

/* CREATE STUDENT */

INSERT into swt.NUTZER(NUTZERID,PASSWORD) VALUES (*NUTZERID*,"PASSWORD");

INSERT into swt.STUDENT(MATRIKELNUMMER,EMAIL,NUTZERID) VALUES (*MATRIKELNUMMER*,EMAIL,NUTZERID);





/* CREATE AUFGABE  */

SELECT MAX(AUFGABENKOMPLEXID) as MAX_ID from AUFGABENKOMPLEX;



INSERT into swt.AUFGABENKOMPLEX(AUFGABENKOMPLEXID,AUFGABEID,MAX,BEWERTET_VON_MAX,DESCRIPTION) VALUES (AUFGABENKOMPLEXID,AUFGABEID,0,0,"")

INSERT into swt.AUFGABENKOMPLEX(AUFGABENKOMPLEXID,DESCRIPTION,) VALUES (AUFGABENKOMPLEXID,"DESCRIPTION",ANZAHL_PUNKTE);


